# RR.Blazor Claude Configuration
project_name: "RR.Blazor"
description: "Enterprise Blazor component library with AI-first documentation"

# Commands available for this project
commands:
  designer: "Elite frontend architect command for creating production-ready UI components"

# Project-specific settings
settings:
  ai_docs_path: "wwwroot/rr-ai-docs.json"
  component_count: "49+"
  utility_classes: "800+"
  css_variables: "200+"
  
# Auto-load resources
auto_load:
  - "wwwroot/rr-ai-docs.json"